### ISSUE TITLE
Katalog Tabelle war nicht intuitiv klickbar / Produkte nicht intuitiv gefunden

### ISSUE THREAD

**Issue by Magichoco** [plab-inc/ReqPal#122]
- [ ] Nutzer haben nach Produkten gesucht in der Katalogübersicht
- [ ] Nutzer wusste nicht, dass Zeilen anklickbar sind in der Tabelle 
- [ ] Hinweise ergänzen oder direkt erste Zeile angeklickt markieren/öffnen

**Comment by TheLethalGoose** [comment]
Abgearbeitet in #118
