### ISSUE TITLE
Studierende sollen z.B. zu Lektionen anstatt zu Dozenten zugeordnet werden

### ISSUE THREAD

**Issue by Magichoco** [plab-inc/ReqPal#129]
- [ ] Studierende zu Dozenten zuzuordnen erschien nicht ideal
- [ ] Studierende sollten in der Lage sein, Lektionen von unterschiedlichen Dozenten bearbeiten zu können 
- [ ] Hierfür können die Dozenten die Studierenden auswählen und einladen
- [ ] Lektionen können z.B. Passwortgeschützt sein, so dass der Dozent die Passwörter mit den Studierenden teilen kann
- [ ] Dadurch können Lektionen auch nur von einzelnen Gruppen bearbeitet werden, anstelle von jedem

**Comment by TheLethalGoose** [comment]
Macht keinen Sinn mehr
