### ISSUE TITLE
Lessons.vue refactor

### ISSUE THREAD

**Issue by Magichoco** [plab-inc/ReqPal#164]
Wie LessonDetailsStudent kann auch eine Komponente für die Lesson Details für den Teacher erstellt werden. Dort können die Buttons ausgelagert werden mit den Funktionen, die nur für den Teacher sichtbar sind.

**Comment by TheLethalGoose** [comment]
Nicht mehr nötig da die alte Lesson Ansicht für Studis verschwindet.
