### ISSUE TITLE
Fortschrittsverfolgung in Lektion

### ISSUE THREAD

**Issue by Magichoco** [plab-inc/ReqPal#37]
- [x] #38 

- [ ] Während einer Übung sollte der Lernende den aktuellen Fortschritt in Bezug auf die Gesamtzahl der Aufgaben oder den Fortschrittsbalken einsehen können.

- [ ] Es sollte eine klare visuelle Darstellung des Fortschritts geben, z. B. durch eine Prozentangabe, eine grafische Anzeige oder eine Anzahl abgeschlossener Aufgaben.

- [x] Der Lernende sollte jederzeit sehen können, welche Aufgaben er bereits abgeschlossen hat und welche noch ausstehen.

- [x] Bei längeren Übungen sollte der Lernende die Möglichkeit haben, zu den bereits abgeschlossenen Aufgaben zurückzukehren und seine Antworten oder Lösungen zu überprüfen.

- [x] Der Lernende sollte in der Lage sein, zwischen den Aufgaben vor- und zurückzugehen, um seinen Fortschritt zu überprüfen und gegebenenfalls Änderungen vorzunehmen.

- [x] Es sollte eine klare Kennzeichnung oder Markierung für abgeschlossene Aufgaben geben, um den Fortschritt leicht erkennen zu können.

- [ ] Der Lernende sollte die Option haben, den Gesamtfortschritt der Übung jederzeit abzurufen, um zu sehen, wie viel er bereits bearbeitet hat und wie viel noch übrig ist.

- [ ] Es sollte eine Zusammenfassung des Fortschritts nach Abschluss der Übung zur Verfügung stehen, um dem Lernenden einen Überblick über seine Leistung zu geben.

**Comment by TheLethalGoose** [comment]
Geschlossen weil es jetzt Szenarien gibt.
